services:

  postgres:
    image: postgres:12.19-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: backend_service_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend-service:
    build:
      context: ../../services/backend-service/
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - 18001:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DEFAULT_SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: backend_service_db
      DB_USERNAME: local
      DB_PASSWORD: local
